version: '3'

services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=$VAULTWARDEN_ADMIN_PASSWORD
    volumes:
      - ${APP_DATA_DIR}/data:/data
