version: "2.1"
services:
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ} # Can use any env variable. List in runtipi/templates/env-sample
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - ${APP_PORT}:8181
    restart: unless-stopped
    networks:
      - tipi_main_network