name: Beta Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Beta version tag (1, 2, 3, ...)'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.create_tag.outputs.tagname }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_suffix: '-beta.${{ github.event.inputs.tag }}'

  build-worker:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/worker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/worker:${{ needs.create-tag.outputs.tagname }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/worker:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/worker:buildcache,mode=max

  build-images:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/runtipi:${{ needs.create-tag.outputs.tagname }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runtipi:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/runtipi:buildcache,mode=max

  build-cli:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Set version
        run: pnpm -r --filter cli set-version ${{ needs.create-tag.outputs.tagname }}

      - name: Build CLI
        run: pnpm -r --filter cli package

      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: cli
          path: packages/cli/dist

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-tag, build-images, build-cli, build-worker]
    outputs:
      id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Download CLI
        uses: actions/download-artifact@v3
        with:
          name: cli
          path: cli

      - name: Create beta release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            **${{ needs.create-tag.outputs.tagname }}**
          tag_name: ${{ needs.create-tag.outputs.tagname }}
          release_name: ${{ needs.create-tag.outputs.tagname }}
          draft: false
          prerelease: true

      - name: Upload X64 Linux CLI binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cli/bin/cli-x64
          asset_name: runtipi-cli-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload ARM64 Linux CLI binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cli/bin/cli-arm64
          asset_name: runtipi-cli-linux-arm64
          asset_content_type: application/octet-stream

  e2e-tests:
    needs: [create-tag, publish-release]
    uses: './.github/workflows/e2e.yml'
    secrets: inherit
    with:
      version: ${{ needs.create-tag.outputs.tagname }}
