name: Release candidate

on:
  workflow_dispatch:

jobs:
  # Build images and publish RCs to DockerHub
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag from VERSION file
        id: meta
        run: |
          VERSION=$(npm run version --silent)
          TAG=${VERSION}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: meienberger/runtipi:rc-${{ steps.meta.outputs.TAG }}
          cache-from: type=registry,ref=meienberger/runtipi:buildcache
          cache-to: type=registry,ref=meienberger/runtipi:buildcache,mode=max
